[{
  "id": 1,
  "name": "King Pizza and Kebab",
  "slug": "king-pizza-and-kebab-bognor",
  "description": "<p><strong>Pellentesque habitant morbi tristique<\/strong> senectus et netus et malesuada fames ac turpis egestas.</p><p> Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. <em>Aenean ultricies mi vitae est.<\/em> Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, <code>commodo vitae<\/code>, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. <a href=\"#\">Donec non enim<\/a> in turpis pulvinar facilisis. Ut felis.<\/p>\r\n\r\n<h2>Header Level 2<\/h2>\r\n\r\n<ol>\r\n   <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.<\/li>\r\n   <li>Aliquam tincidunt mauris eu risus.<\/li>\r\n<\/ol>",
  "allergies": "<p><strong>Allergen information provided by the restaurant. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. <em>Aenean ultricies mi vitae est.<\/em> Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, <code>commodo vitae<\/code>, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. <a href=\"#\">Donec non enim<\/a> in turpis pulvinar facilisis. Ut felis.<\/p>\r\n\r\n<h2>Header Level 2<\/h2>\r\n\r\n<ol>\r\n   <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.<\/li>\r\n   <li>Aliquam tincidunt mauris eu risus.<\/li>\r\n<\/ol>",
  "facebook_url": "",
  "twitter_url": "",
  "youtube_url": "",
  "contact_number": "01243 999000",
  "open_now": true,
  "order_now": true,
  "order_from": [
    [0900, 2300],
    [0900, 2300],
    [0900, 2300],
    [0900, 2300],
    [0900, 2300],
    [0900, 2300],
    [0900, 2300]
  ],
  "opening_hours": [
    [1300, 2300],
    [1300, 2300],
    [1300, 2300],
    [1300, 2300],
    [1300, 2300],
    [1300, 2300],
    [1300, 2300]
  ],
  "featured_categories": [
    "kebab",
    "pizza",
    "pasta",
    "burgers",
    "wraps"
  ],
  "rating": 2,
  "rating_count": "345",
  "hygiene_rating": "4",
  "collection_lead_time": "15",
  "delivery_lead_time": "45",
  "address": "123 The Street, Townsville, Sussex, PO11 1OP",
  "lat": "-51.1123",
  "lng": "2.1231",
  "distance" : 4.5,
  "logo_url": "/images/restaurants/logo-for-king.jpg",
  "cover_url": "/images/restaurants/cover-for-king.jpg",
  "delivery_minimum_spend": 12.00,
  "delivery_fee": 2
},
{
  "id": 1,
  "name": "Duchess Pizza and Kebab",
  "slug": "king-pizza-and-kebab-bognor",
  "description": "<p><strong>Pellentesque habitant morbi tristique<\/strong> senectus et netus et malesuada fames ac turpis egestas.</p><p> Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. <em>Aenean ultricies mi vitae est.<\/em> Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, <code>commodo vitae<\/code>, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. <a href=\"#\">Donec non enim<\/a> in turpis pulvinar facilisis. Ut felis.<\/p>\r\n\r\n<h2>Header Level 2<\/h2>\r\n\r\n<ol>\r\n   <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.<\/li>\r\n   <li>Aliquam tincidunt mauris eu risus.<\/li>\r\n<\/ol>",
  "allergies": "<p><strong>Allergen information provided by the restaurant. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. <em>Aenean ultricies mi vitae est.<\/em> Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, <code>commodo vitae<\/code>, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. <a href=\"#\">Donec non enim<\/a> in turpis pulvinar facilisis. Ut felis.<\/p>\r\n\r\n<h2>Header Level 2<\/h2>\r\n\r\n<ol>\r\n   <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.<\/li>\r\n   <li>Aliquam tincidunt mauris eu risus.<\/li>\r\n<\/ol>",
  "facebook_url": "",
  "twitter_url": "",
  "youtube_url": "",
  "contact_number": "01243 999000",
  "open_now": false,
  "order_now": true,
  "order_from": [
    [1100, 2300],
    [1100, 2300],
    [1100, 2300],
    [1100, 2300],
    [1100, 2300],
    [1100, 2300],
    [1100, 2300]
  ],
  "opening_hours": [
    [1100, 2300],
    [1100, 2300],
    [1100, 2300],
    [1100, 2300],
    [1100, 2300],
    [1100, 2300],
    [1100, 2300]
  ],
  "featured_categories": [
    "kebab",
    "pizza",
    "pasta",
    "burgers",
    "wraps"
  ],
  "rating": 2,
  "rating_count": "345",
  "hygiene_rating": "4",
  "collection_lead_time": "15",
  "delivery_lead_time": "45",
  "address": "123 The Street, Townsville, Sussex, PO11 1OP",
  "lat": "-51.1123",
  "lng": "2.1231",
  "distance" : 4.5,
  "logo_url": "/images/restaurants/logo-for-king.jpg",
  "cover_url": "/images/restaurants/cover-for-king.jpg",
  "delivery_minimum_spend": 12.00,
  "delivery_fee": 2
},
{
  "id": 1,
  "name": "Count Pizza and Kebab",
  "slug": "king-pizza-and-kebab-bognor",
  "description": "<p><strong>Pellentesque habitant morbi tristique<\/strong> senectus et netus et malesuada fames ac turpis egestas.</p><p> Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. <em>Aenean ultricies mi vitae est.<\/em> Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, <code>commodo vitae<\/code>, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. <a href=\"#\">Donec non enim<\/a> in turpis pulvinar facilisis. Ut felis.<\/p>\r\n\r\n<h2>Header Level 2<\/h2>\r\n\r\n<ol>\r\n   <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.<\/li>\r\n   <li>Aliquam tincidunt mauris eu risus.<\/li>\r\n<\/ol>",
  "allergies": "<p><strong>Allergen information provided by the restaurant. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. <em>Aenean ultricies mi vitae est.<\/em> Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, <code>commodo vitae<\/code>, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. <a href=\"#\">Donec non enim<\/a> in turpis pulvinar facilisis. Ut felis.<\/p>\r\n\r\n<h2>Header Level 2<\/h2>\r\n\r\n<ol>\r\n   <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.<\/li>\r\n   <li>Aliquam tincidunt mauris eu risus.<\/li>\r\n<\/ol>",
  "facebook_url": "",
  "twitter_url": "",
  "youtube_url": "",
  "contact_number": "01243 999000",
  "open_now": false,
  "order_now": false,
  "order_from": [
    [1300, 2300],
    [1300, 2300],
    [1300, 2300],
    [1300, 2300],
    [1300, 2300],
    [1100, 2300],
    [1100, 2300]
  ],
  "opening_hours": [
    [1400, 2300],
    [1400, 2300],
    [1400, 2300],
    [1400, 2300],
    [1400, 2300],
    [1400, 2300],
    [1400, 2300]
  ],
  "featured_categories": [
    "kebab",
    "pizza",
    "pasta",
    "burgers",
    "wraps"
  ],
  "rating": 2,
  "rating_count": "345",
  "hygiene_rating": "4",
  "collection_lead_time": "15",
  "delivery_lead_time": "45",
  "address": "123 The Street, Townsville, Sussex, PO11 1OP",
  "lat": "-51.1123",
  "lng": "2.1231",
  "distance" : 4.5,
  "logo_url": "/images/restaurants/logo-for-king.jpg",
  "cover_url": "/images/restaurants/cover-for-king.jpg",
  "delivery_minimum_spend": 12.00,
  "delivery_fee": 2
},
{
  "id": 1,
  "name": "Duke Pizza and Kebab",
  "slug": "king-pizza-and-kebab-bognor",
  "description": "<p><strong>Pellentesque habitant morbi tristique<\/strong> senectus et netus et malesuada fames ac turpis egestas.</p><p> Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. <em>Aenean ultricies mi vitae est.<\/em> Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, <code>commodo vitae<\/code>, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. <a href=\"#\">Donec non enim<\/a> in turpis pulvinar facilisis. Ut felis.<\/p>\r\n\r\n<h2>Header Level 2<\/h2>\r\n\r\n<ol>\r\n   <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.<\/li>\r\n   <li>Aliquam tincidunt mauris eu risus.<\/li>\r\n<\/ol>",
  "allergies": "<p><strong>Allergen information provided by the restaurant. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. <em>Aenean ultricies mi vitae est.<\/em> Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, <code>commodo vitae<\/code>, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. <a href=\"#\">Donec non enim<\/a> in turpis pulvinar facilisis. Ut felis.<\/p>\r\n\r\n<h2>Header Level 2<\/h2>\r\n\r\n<ol>\r\n   <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.<\/li>\r\n   <li>Aliquam tincidunt mauris eu risus.<\/li>\r\n<\/ol>",
  "facebook_url": "",
  "twitter_url": "",
  "youtube_url": "",
  "contact_number": "01243 999000",
  "open_now": true,
  "order_now": true,
  "order_from": [
    [1000, 2200],
    [1000, 2200],
    [1000, 2200],
    [1000, 2200],
    [1000, 2200],
    [1000, 2200],
    [1000, 2200]
  ],
  "opening_hours": [
    [1100, 2000],
    [1100, 2000],
    [1100, 2000],
    [1100, 2000],
    [1100, 2000],
    [1100, 2000],
    [1100, 2000]
  ],
  "featured_categories": [
    "kebab",
    "pizza",
    "pasta",
    "burgers",
    "wraps"
  ],
  "rating": 2,
  "rating_count": "345",
  "hygiene_rating": "4",
  "collection_lead_time": "15",
  "delivery_lead_time": "45",
  "address": "123 The Street, Townsville, Sussex, PO11 1OP",
  "lat": "-51.1123",
  "lng": "2.1231",
  "distance" : 4.5,
  "logo_url": "/images/restaurants/logo-for-king.jpg",
  "cover_url": "/images/restaurants/cover-for-king.jpg",
  "delivery_minimum_spend": 12.00,
  "delivery_fee": 2
},
{
  "id": 1,
  "name": "Prince Pizza and Kebab",
  "slug": "king-pizza-and-kebab-bognor",
  "description": "<p><strong>Pellentesque habitant morbi tristique<\/strong> senectus et netus et malesuada fames ac turpis egestas.</p><p> Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. <em>Aenean ultricies mi vitae est.<\/em> Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, <code>commodo vitae<\/code>, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. <a href=\"#\">Donec non enim<\/a> in turpis pulvinar facilisis. Ut felis.<\/p>\r\n\r\n<h2>Header Level 2<\/h2>\r\n\r\n<ol>\r\n   <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.<\/li>\r\n   <li>Aliquam tincidunt mauris eu risus.<\/li>\r\n<\/ol>",
  "allergies": "<p><strong>Allergen information provided by the restaurant. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. <em>Aenean ultricies mi vitae est.<\/em> Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, <code>commodo vitae<\/code>, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. <a href=\"#\">Donec non enim<\/a> in turpis pulvinar facilisis. Ut felis.<\/p>\r\n\r\n<h2>Header Level 2<\/h2>\r\n\r\n<ol>\r\n   <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.<\/li>\r\n   <li>Aliquam tincidunt mauris eu risus.<\/li>\r\n<\/ol>",
  "facebook_url": "",
  "twitter_url": "",
  "youtube_url": "",
  "contact_number": "01243 999000",
  "open_now": true,
  "order_now": true,
  "order_from": [
    [1100, 2300],
    [1100, 2300],
    [1100, 2300],
    [1100, 2300],
    [1100, 2300],
    [1100, 2300],
    [1100, 2300]
  ],
  "opening_hours": [
    [1100, 2300],
    [1100, 2300],
    [1100, 2300],
    [1100, 2300],
    [1100, 2300],
    [1100, 2300],
    [1100, 2300]
  ],
  "featured_categories": [
    "kebab",
    "pizza",
    "pasta",
    "burgers",
    "wraps"
  ],
  "rating": 2,
  "rating_count": "345",
  "hygiene_rating": "4",
  "collection_lead_time": "15",
  "delivery_lead_time": "45",
  "address": "123 The Street, Townsville, Sussex, PO11 1OP",
  "lat": "-51.1123",
  "lng": "2.1231",
  "distance" : 4.5,
  "logo_url": "/images/restaurants/logo-for-king.jpg",
  "cover_url": "/images/restaurants/cover-for-king.jpg",
  "delivery_minimum_spend": 12.00,
  "delivery_fee": 2
},
{
  "id": 1,
  "name": "Queen Pizza and Kebab",
  "slug": "king-pizza-and-kebab-bognor",
  "description": "<p><strong>Pellentesque habitant morbi tristique<\/strong> senectus et netus et malesuada fames ac turpis egestas.</p><p> Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. <em>Aenean ultricies mi vitae est.<\/em> Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, <code>commodo vitae<\/code>, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. <a href=\"#\">Donec non enim<\/a> in turpis pulvinar facilisis. Ut felis.<\/p>\r\n\r\n<h2>Header Level 2<\/h2>\r\n\r\n<ol>\r\n   <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.<\/li>\r\n   <li>Aliquam tincidunt mauris eu risus.<\/li>\r\n<\/ol>",
  "allergies": "<p><strong>Allergen information provided by the restaurant. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. <em>Aenean ultricies mi vitae est.<\/em> Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, <code>commodo vitae<\/code>, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. <a href=\"#\">Donec non enim<\/a> in turpis pulvinar facilisis. Ut felis.<\/p>\r\n\r\n<h2>Header Level 2<\/h2>\r\n\r\n<ol>\r\n   <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.<\/li>\r\n   <li>Aliquam tincidunt mauris eu risus.<\/li>\r\n<\/ol>",
  "facebook_url": "",
  "twitter_url": "",
  "youtube_url": "",
  "contact_number": "01243 999000",
  "open_now": true,
  "order_now": true,
  "order_from": [
    [1100, 2300],
    [1100, 2300],
    [1100, 2300],
    [1100, 2300],
    [1100, 2300],
    [1100, 2300],
    [1100, 2300]
  ],
  "opening_hours": [
    [1100, 2300],
    [1100, 2300],
    [1100, 2300],
    [1100, 2300],
    [1100, 2300],
    [1100, 2300],
    [1100, 2300]
  ],
  "featured_categories": [
    "kebab",
    "pizza",
    "pasta",
    "burgers",
    "wraps"
  ],
  "rating": 2,
  "rating_count": "345",
  "hygiene_rating": "4",
  "collection_lead_time": "15",
  "delivery_lead_time": "45",
  "address": "123 The Street, Townsville, Sussex, PO11 1OP",
  "lat": "-51.1123",
  "lng": "2.1231",
  "distance" : 4.5,
  "logo_url": "/images/restaurants/logo-for-king.jpg",
  "cover_url": "/images/restaurants/cover-for-king.jpg",
  "delivery_minimum_spend": 12.00,
  "delivery_fee": 2
}]
